### ISSUE TITLE
Javascript: Facebook partial only load the first time 

### ISSUE THREAD

**Issue by juansecaro** [juansecaro/guialocal#2]
Facebook partial only load the first time and then disappear  if you go visiting through the page. If you upload, then it show up again.

The expected behabiour should be always to be there, in all and every page.

**Comment by juansecaro** [comment]
Ok

**Comment by Bytheway001** [comment]
Please provide some information when closing issues, is a good way to track "what happened" after it is solved, this time I'll add it.
- The issue was indeed turbolinks, came with a workaround detaching/reattaching the widget generated tag
