### ISSUE TITLE
Weather slider load just once

### ISSUE THREAD

**Issue by juansecaro** [juansecaro/guialocal#4]
Diferently to the facebook like wiget, here API won't support so many calls, so it is convenient some kind of hourly caché.

It must be taken into consideration that the current planing require 1 script with specific data on each city. Right now, this is done placing it in the folder cities, and using the environment var "current city".

**Comment by Bytheway001** [comment]
Won't handle this as a bug, moreof as an enhacement, since it is working fine, just have to limit the number of calls. Working on it at this moment

**Comment by juansecaro** [comment]
Let's keep that aside from a time. It's seems right now works quite allright.
