### ISSUE TITLE
Promo upload image fails when size limit surpass

### ISSUE THREAD

**Issue by juansecaro** [juansecaro/guialocal#5]
When someone tries to upload a file with a size limit bigger than the amount set in the server, an error appear (those one that provides no information). The situation should be handled providing information about the problem to the use in a friendly maner, rescuing the Excepcion.

Also, It must be checked that Carrierwave is compresing the final outcome (I believe this is already done)

**Comment by Bytheway001** [comment]
I'm thinking on a client approach, validating filesize before sending the request, also It was not clear if you meant Dimensions (cm) or actual file size (Kb) clarify this and come back to me, I'll handle that

**Comment by juansecaro** [comment]
Ideally we should make both, client and server side. Right now the validation set limits on KB.
Right now it's 500 kb, but since most people is having trouble I thought about incrising to 3 MB and try letting imagemagick make some compressions
